# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=25)),
                ('street', models.CharField(max_length=80, verbose_name='Ulica')),
                ('postalcode', models.CharField(max_length=20, verbose_name='Kod pocztowy')),
                ('city', models.CharField(max_length=50, verbose_name='Miasto')),
            ],
        ),
        migrations.CreateModel(
            name='Bailiffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('companyName', models.CharField(max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('adress_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Adresses')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('colorCode', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Company_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyType', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baillif_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Bailiffs')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts_groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactsGroup', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Correspondencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivedSentDate', models.DateTimeField(verbose_name='Data wysyłki')),
                ('writingDate', models.DateTimeField(verbose_name='Data napisania')),
                ('signature', models.CharField(max_length=25, verbose_name='Podpis')),
                ('autoNumeration', models.IntegerField(default=0)),
                ('subject', models.CharField(max_length=25, verbose_name='Temat')),
                ('dueDate', models.DateTimeField(verbose_name='Data do której należy odpisać')),
                ('scannedDocument', models.CharField(max_length=25, verbose_name='Skanuj dokument')),
                ('fileName', models.CharField(max_length=25, verbose_name='Nazwa pliku')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Clients')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Contacts')),
                ('contactsGroup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Contacts_groups')),
            ],
        ),
        migrations.CreateModel(
            name='Correspondency_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Typ korespondencji')),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Courts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=25, verbose_name='Urząd')),
                ('department', models.CharField(max_length=50, verbose_name='Wydział')),
                ('www', models.CharField(max_length=25, verbose_name='www')),
                ('adress_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Adresses')),
            ],
        ),
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=25, verbose_name='Urząd')),
                ('name', models.CharField(max_length=25, verbose_name='Imię')),
                ('lastname', models.CharField(max_length=25, verbose_name='Nazwisko')),
                ('adress_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Adresses')),
                ('companyType_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Company_types')),
            ],
        ),
        migrations.CreateModel(
            name='Mentioned_clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Wymienione kontakty')),
            ],
        ),
        migrations.AlterField(
            model_name='upadly',
            name='nazwaUpadlego_text',
            field=models.CharField(max_length=300, verbose_name='Nazwa Upadłego'),
        ),
        migrations.AlterField(
            model_name='upadly',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Data Publikacji'),
        ),
        migrations.AddField(
            model_name='correspondencies',
            name='correspondencyType_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Correspondency_type'),
        ),
        migrations.AddField(
            model_name='correspondencies',
            name='mentionedClient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Mentioned_clients'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='court_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Courts'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='legal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Legal'),
        ),
        migrations.AddField(
            model_name='clients',
            name='folder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Folders'),
        ),
        migrations.AddField(
            model_name='bailiffs',
            name='companyType_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Company_types'),
        ),
        migrations.AddField(
            model_name='adresses',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Countries'),
        ),
    ]
