# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20170421_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Upadlosc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Nazwa Upadłości')),
                ('symbol', models.CharField(max_length=50, unique=True, verbose_name='Symbol')),
                ('pub_date', models.DateTimeField(verbose_name='Data Publikacji')),
                ('colorCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.ColorCode')),
            ],
        ),
        migrations.AlterField(
            model_name='upadly',
            name='nazwaUpadlego_text',
            field=models.CharField(max_length=300, unique=True, verbose_name='Nazwa Upadłego'),
        ),
    ]
