# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20170423_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upadly',
            name='nazwaUpadlego_text',
            field=models.CharField(max_length=300, verbose_name='Nazwa Upadłego'),
        ),
    ]
