# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20170423_2230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upadly',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='nazwaUpadlego_text',
            new_name='name_text',
        ),
    ]
