# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20170423_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts_groups',
            old_name='contactsGroup',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(default=163, max_length=25),
        ),
    ]
