# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20170426_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courts',
            name='companyName',
            field=models.CharField(max_length=300, verbose_name='Nazwa sądu:'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='department',
            field=models.CharField(max_length=50, verbose_name='Wydział:'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='www',
            field=models.CharField(max_length=100, verbose_name='www:'),
        ),
    ]
